CREATE DATABASE INSURANCE;
SELECT * FROM INSURANCE.BROKERAGE;
SELECT * FROM INSURANCE.FEES;
SELECT * FROM INSURANCE.INDI;
SELECT * FROM INSURANCE.INVOICE;
SELECT * FROM INSURANCE.MEETING;
SELECT * FROM INSURANCE.OPPORTUNITY;

USE INSURANCE;

-- TARGET AND INVOICE AMOUNT OF CROSS SELL

SELECT
	(SELECT SUM(CSB) FROM INDI) AS TARGET_CROSS_SELL,        
    (SELECT SUM(AMOUNT)
    FROM INVOICE
    WHERE INCOME_CLASS='Cross Sell') AS INVOICE_CROSS_SELL;
    
-- ACHIEVEMENT AMOUNT OF CROSS SELL
    
SELECT
    SUM(AMOUNT_1) AS CROSS_SELL_ACHIEVEMENT
FROM (
	SELECT AMOUNT_1
    FROM FEES
    WHERE INCOME_CLASS='CROSS SELL'
    UNION ALL
    SELECT AMOUNT_2
    FROM BROKERAGE
    WHERE INCOME_CLASS='CROSS SELL'
) AS COMBINED;

-- TARGET AND INVOICE AMOUNT OF NEW

SELECT
(SELECT SUM(NB) FROM INDI) AS TARGET_NEW,
(SELECT SUM(COALESCE(AMOUNT, 0))
FROM INVOICE
WHERE INCOME_CLASS='NEW') AS INVOICE_NEW;

-- ACHIEVEMENT AMOUNT OF NEW   

	SELECT
    SUM(AMOUNT_1) AS NEW_ACHIEVEMENT
FROM (
	SELECT AMOUNT_1
    FROM FEES
    WHERE INCOME_CLASS='NEW'
    UNION ALL
    SELECT AMOUNT_2
    FROM BROKERAGE
    WHERE INCOME_CLASS='NEW'
) AS COMBINED;

-- TARGET AND INVOICE AMOUNT OF RENEWAL

 SELECT
(SELECT SUM(RB)
FROM INDI) AS TARGET_RENEWAL,
(SELECT SUM(COALESCE(AMOUNT, 0))
 FROM INVOICE
WHERE INCOME_CLASS='RENEWAL') AS INVOICE_RENEWAL;

-- ACHIEVEMENT AMOUNT OF RENEWAL

SELECT
	SUM(AMOUNT_1) AS RENEWAL_ACHIEVEMENT
FROM(
	SELECT AMOUNT_1
    FROM FEES
    WHERE INCOME_CLASS='RENEWAL'
    UNION ALL
    SELECT AMOUNT_2
    FROM BROKERAGE
    WHERE INCOME_CLASS='RENEWAL'
) AS COMBINED;

-- CROSS SELL PLACED AND INVOICE ACHIEVEMENT

SELECT (13041253.3/20083111*100) AS CROSS_SELL_PLACED_ACHIEVEMENT;
SELECT (3040813/20083111*100) AS CROSS_SELL_INVOICE_ACHIEVEMENT;

-- NEW PLACED AND INVOICE ACHIEVEMENT

 SELECT (3531629.30/19673793*100) AS NEW_PLACED_ACHIEVEMENT;
 SELECT (827822/19673793*100) AS NEW_INVOICE_ACHIEVEMENT;
 
 -- RENEWAL PLACED AND INVOICE ACHIEVEMENT
 
 SELECT (18507270.64/12319455*100) AS RENEWAL_PLACED_ACHIEVEMENT;
 SELECT (8394071/12319455*100) AS INVOICE_PLACED_ACHIEVEMENT;
 
 -- NO.OF MEETING BY ACCOUNT EXECUTIVE
 
SELECT AE, COUNT(MEETING_DATE) AS MEETING_COUNT
FROM MEETING
GROUP BY AE;

-- NO.OF INVOICE BY ACCOUNT EXECUTIVE

SELECT AE, COUNT(INVOICE_DATE) AS INVOICE_COUNT
FROM INVOICE
GROUP BY AE;

-- STAGE FUNNEL BY REVENUE

SELECT STAGE, SUM(REVENUE_AMOUNT)
FROM OPPORTUNITY
GROUP BY STAGE;

-- TOTAL OPPORTUNITY

SELECT COUNT(STAGE) AS TOTAL_OPPORTUNITY
FROM OPPORTUNITY;

-- TOTAL OPEN OPPORTUNITY

SELECT COUNT(STAGE) AS TOTAL_OPEN_OPPORTUNITY
FROM OPPORTUNITY
WHERE STAGE NOT IN ('NEGOTIATE');

-- TOP 5 OPEN OPPORTUNITY

SELECT OPPORTUNITY_NAME, REVENUE_AMOUNT
FROM OPPORTUNITY
ORDER BY REVENUE_AMOUNT DESC
LIMIT 5;

-- YEAR WISE MEETING COUNT

SELECT MEETING_DATE AS YEAR, COUNT(MEETING_DATE) AS MEETINGCOUNT
FROM MEETING
GROUP BY MEETING_DATE
ORDER BY MEETING_DATE;